import pytest

from PTT.handlers import add_defaults
from PTT.parse import Parser


@pytest.fixture
def parser():
    p = Parser()
    add_defaults(p)
    return p




@pytest.mark.parametrize("release_name, expected_languages", [
    ("Deadpool 2016 1080p BluRay DTS Rus Ukr 3xEng HDCL", ["russian", "ukrainian"]),
    ("VAIANA: MOANA (2017) NL-Retail [2D] EAGLE", ["dutch"]),
    ("De Noodcentrale S02E05 FLEMISH 540p WEBRip AAC H 264", ["dutch"]),
    ("The Intern 2015 TRUEFRENCH 720p BluRay x264-PiNKPANTERS", ["french"]),
    ("After Earth 2013 VFF BDrip x264 YJ", ["french"]),
    ("127.Heures.FRENCH.DVDRip.AC3.XViD-DVDFR", ["french"]),
    ("Color.Of.Night.Unrated.DC.VostFR.BRrip.x264", ["french"]),
    ("Le Labyrinthe 2014 Multi-VF2 1080p BluRay x264-PopHD", ["multi audio"]),
    ("Maman, j'ai raté l'avion 1990 VFI 1080p BluRay DTS x265-HTG", ["french"]),
    ("South.Park.S21E10.iTALiAN.FiNAL.AHDTV.x264-NTROPiC", ["italian"]),
    ("2- English- {SDH}.srt", ["english"]),
    ("1_ English-Subs.srt", ["english"]),
    ("House S 1 CD 1-6 svensk, danska, norsk, finsk sub", ["danish", "finnish", "swedish", "norwegian"]),
    ("Svein.Og.Rotta.NORSK.Nordic.Subs.2006", ["danish", "finnish", "swedish", "norwegian"]),
    ("Borat med Norsk Undertekst", ["norwegian"]),
    ("Subs/21_Bokmal.srt", ["norwegian"]),
    ("Subs/nob.srt", ["norwegian"]),
    ("Subs/5_nor.srt", ["norwegian"]),
    ("Curious.George.2.Follow.That.Monkey.2009.DK.SWE.UK.PAL.DVDR-CATC", ["danish", "swedish"]),
    ("Yes.Man.Dk-Subs.2009.dingel", ["danish"]),
    ("Dan-SDH.srt", ["danish"]),
    ("dan.srt", ["danish"]),
    ("Red Riding 1974 [2009 PAL DVD][En Subs[Sv.No.Fi]", ["english", "finnish", "swedish"]),
    ("Comme une Image (Look at Me) [2004 PAL DVD][Fr Subs[Sv.Da.No]", ["french", "swedish"]),
    ("A.Good.Day.To.Die.Hard.2013.SWESUB.DANSUB.FiNSUB.720p.WEB-DL.-Ro", ["danish", "finnish", "swedish"]),
    ("The.Prisoner.1967-1968.Complete.Series.Subs.English+Nordic", ["english", "danish", "finnish", "swedish", "norwegian"]),
    ("Royal.Pains.S05E02.HDTV.subtitulado.esp.sc.avi", ["spanish"]),
    ("Desmembrados (2006) [HDrip-XviD-AC3][Castellano]", ["spanish"]),
    ("10_Spanish-Subs.srt", ["spanish"]),
    ("Patriot Games [1992] Eng, Ger, Cze, Hun, Pol + multisub  DVDrip", ["multi subs", "english", "german", "polish", "czech", "hungarian"]),
    ("Elvis Presley - La via del Male (King creole) - IT EN FR DE ES", ["english", "french", "spanish", "italian", "german"]),
    ("FernGully [H264 - Ita Dut Fre Ger Eng Spa Aac - MultiSub]", ["multi subs", "english", "french", "spanish", "italian", "german", "dutch"]),
    ("Jesus de Montreal / Jesus of Montreal - subtitulos espanol", ["spanish"]),
    ("Los.Vengadores.DVDR español ingles clon", ["english", "spanish"]),
    ("EMPIRE STATE 2013 DVDRip TRNC English and Española Latin", ["english", "spanish"]),
    ("Mary Poppins Returns 2019 DVDRip LATINO-1XBET", ["latino"]),
    ("Los Simpsons S18 E01 Latino", ["latino"]),
    ("Spider-Man (2002) Blu-Ray [720p] Dual Ingles-Español", ["dual audio", "english", "spanish"]),
    ("Abuela (2015) 1080p BluRay x264 AC3 Dual Latino-Inglés", ["dual audio", "english", "latino"]),
    ("Dumbo.2019.1080p.Dual.Lat", ["dual audio", "latino"]),
    ("A.Score.to.Settle.2019.lati.mp4", ["latino"]),
    ("[S0.E04] Gambit królowej - Gra środkowa.Spanish Latin America.srt", ["latino"]),
    ("Latin American.spa.srt", ["latino"]),
    ("Men in Black International 2019 (inglês português)", ["english", "portuguese"]),
    ("Assassins (1995) Sylvester Stallone.DVDrip.XviD - Italian Englis", ["english", "italian"]),
    ("El Club de la Lucha[dvdrip][spanish]", ["spanish"]),
    ("The Curse Of The Weeping Woman 2019 BluRay 1080p Tel+Tam+hin+eng", ["english", "hindi", "telugu", "tamil"]),
    ("Inception 2010 1080p BRRIP[dual-audio][eng-hindi]", ["dual audio", "english", "hindi"]),
    ("Inception (2010) 720p BDRip Tamil+Telugu+Hindi+Eng", ["english", "hindi", "telugu", "tamil"]),
    ("Subs/Dear.S01E02.WEBRip.x265-ION265/34_tam.srt", ["tamil"]),
    ("Subs/Dear.S01E02.WEBRip.x265-ION265/35_tel.srt", ["telugu"]),
    ("Dabangg 3 2019 AMZN WebRip Hindi 720p x264", ["hindi"]),
    ("Quarantine [2008] [DVDRiP.XviD-M14CH0] [Lektor PL] [Arx]", ["polish"]),
    ("The Mandalorian S01E06 POLISH WEBRip x264-FLAME", ["polish"]),
    ("Carros 2 Dublado - Portugues BR (2011)", ["portuguese"]),
    ("A.Simple.Plan.1998.720p.BDRIP.X264.dublado.portugues.BR.gmenezes", ["portuguese"]),
    ("American.Horror.Story.S01E01.720p. PORTUGUÊS BR", ["portuguese"]),
    ("Angel.S05E19.legendado.br.rmvb", ["portuguese"]),
    ("Grimm S01E11 Dublado BR [ kickUploader ]", ["portuguese"]),
    ("InuYasha.EP161.ptBR.subtitles.[inuplace.com.br].avi", ["portuguese"]),
    ("Ghost.Rider.DivX_Gamonet(Ingles-Port.BR)-AC3.avi", ["english", "portuguese"]),
    ("I Am David  legendado pt/br", ["portuguese"]),
    ("Lone Wolf and Cub 6 movies - legendas BR", ["portuguese"]),
    ("Wonder Woman Season 3 (H.264 1080p; English/Portuguese-BR)", ["english", "portuguese"]),
    ("MIB 3 - Homens de Preto 2012 ( Audio EN-BR - Leg BR  Mkv 1280x69", ["english", "portuguese"]),
    ("my wife is a gangster 3 legendado em PT(BR)", ["portuguese"]),
    ("A.Clockwork.Orange.1971.BRDRIP.1080p.DUAL.PORT-BR.ENG.gmenezes.m", ["dual audio", "english", "portuguese"]),
    ("Superman I - O Filme 1978 Leg. BR - Mkv 1280x528", ["portuguese"]),
    ("Subs/Brazilian.por.srt", ["portuguese"]),
    ("Brazilian Portuguese.por.srt", ["portuguese"]),
    ("[S0.E07] Gambit królowej - Gra końcowa.Portuguese Brazil.srt", ["portuguese"]),
    ("The Hit List (2011) DVD NTSC WS (eng-fre-pt-spa) [Sk]", ["english", "french", "spanish"]), # TODO: does not include pt
    ("[POPAS] Neon Genesis Evangelion: The End of Evangelion [jp_PT-pt", ["japanese", "portuguese"]),
    ("Zola Maseko - Drum (2004) PT subs", ["portuguese"]),
    ("Idrissa Ouedraogo - Yaaba (1989) EN ES FR PT", ["english", "french", "spanish"]), # TODO: does not include pt
    ("Metallica.Through.The.Never.2013 O Filme(leg.pt-pt)", ["portuguese"]),
    ("Dinossauro (2000) --[ Ing / Pt / Esp ]", ["english", "spanish"]), # TODO: does not include pt
    ("The Guard 2011.DK.EN.ES.HR.NL.PT.RO.Subtitles", ["english", "spanish", "romanian", "croatian", "dutch", "danish"]),
    ("Titan.A.E.2000 720p  HDTV DTS Eng Fra Hun Rom Rus multisub", ["multi subs", "english", "french", "russian", "hungarian", "romanian"]),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.Latin American es.ass", ["latino"]),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.Brazilian pt.ass", ["portuguese"]),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.pt.ass", ["portuguese"]),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.es.ass", ["spanish"]),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.de.ass", ["german"]),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.it.ass", ["italian"]),
    ("Frieren - Beyond Journey's End - S01E01 - TBA WEBDL-1080p.ar.ass", ["arabic"]),
    ("Subs(ara,fre,ger).srt", ["french", "german", "arabic"]),
    ("Subs(chi,eng,ind,kor,may,tha,vie).srt", ["korean", "chinese", "vietnamese", "indonesian", "thai", "malay"]),
    ("Miami.Bici.2020.1080p.NETFLIX.WEB-DL.DDP5.1.H.264.EN-ROSub-ExtremlymTorrents", ["english", "romanian"]),
    ("26_Romanian.srt", ["romanian"]),
    ("4_Bulgarian.srt", ["bulgarian"]),
    ("18_srp.srt", ["serbian"]),
    ("Aranyelet.S01.HUNGARIAN.1080p.WEBRip.DDP5.1.x264-SbR[rartv]", ["hungarian"]),
    ("Ponyo[2008]DvDrip-H264 Quad Audio[Eng Jap Fre Spa]AC3 5.1[DXO]", ["english", "japanese", "french", "spanish"]),
    ("The Mechanic [1972] Eng,Deu,Fra,Esp,Rus + multisub DVDrip", ["multi subs", "english", "french", "spanish", "german", "russian"]),
    ("Mommie Dearest [1981 PAL DVD][En.De.Fr.It.Es Multisubs[18]", ["multi subs", "english", "french", "spanish", "german"]), # TODO: does not include it
    ("Pasienio sargyba S01E03 (2016 WEBRip LT)", ["lithuanian"]),
    ("24_Lithuanian.srt", ["lithuanian"]),
    ("25_Latvian.srt", ["latvian"]),
    ("13_Estonian.srt", ["estonian"]),
    ("Ip.Man.4.The.Finale.2019.CHINESE.1080p.BluRay.x264.TrueHD.7.1.Atmos-HDC", ["chinese"]),
    ("should parse CHT language", ["chinese"]),
    ("Inuyasha_TV+Finale+OVA+Film+CD+Manga+Other; dub jpn,chn,eng sub chs (2019-09-21)", ["english", "japanese", "chinese"]),
    ("Initial D Live Action 2005 ENG/CHI", ["english", "chinese"]),
    ("Wolf.Warrior.2015.720p.BluRay.x264.Mandarin.AAC-ETRG", ["chinese"]),
    ("9_zh-Hans.srt", ["chinese"]),
    ("Traditional Chinese.chi.srt", ["taiwanese"]),
    ("Subs/Promare - Chinese (Traditional).ass", ["taiwanese"]),
    ("10_zh-Hant.srt", ["taiwanese"]),
    ("Berserk 01-25 [dual audio JP,EN] MKV", ["dual audio", "english", "japanese"]),
    ("FLCL S05.1080p HMAX WEB-DL DD2.0 H 264-VARYG (FLCL: Shoegaze Dual-Audio Multi-Subs)", ["multi subs", "dual audio"]),
    ("Shinjuku Swan 2015 JAP 1080p BluRay x264 DTS-JYK", ["japanese"]),
    ("Wet.Woman.in.the.Wind.2016.JAPANESE.1080p.BluRay.x264-iKiW", ["japanese"]),
    ("All.Love.E146.KOR.HDTV.XViD-DeBTV", ["korean"]),
    ("The.Nun.2018.KORSUB.HDRip.XviD.MP3-STUTTERSHIT", ["korean"]),
    ("Burning.2018.KOREAN.720p.BluRay.H264.AAC-VXT", ["korean"]),
    ("Atonement.2017.KOREAN.ENSUBBED.1080p.WEBRip.x264-VXTT", ["english", "korean"]),
    ("A Freira (2018) Dublado HD-TS 720p", ["portuguese"]),
    ("Escobar El Patron Del Mal Capitulo 91 SD (2012-10-10) [SiRaDuDe]", ["portuguese"]),
    ("Bleach - 215 ao 220 - [DB-BR]", ["portuguese"]),
    ("Joker.2019.MULTi.Bluray.1080p.Atmos.7.1.En.Fr.Sp.Pt-DDR[EtHD]", ["multi audio", "english", "french"]), # TODO: does not include sp,pt
    ("Dilbert complete series + en subs", ["english"]),
    ("The Next Karate Kid (1994) NTSC WS -Eng/Fre/Spa/Por- [ctang]", ["english", "french", "spanish", "portuguese"]),
    ("arsenico por compasion 1944 Capra spanish castellano", ["spanish"]),
    ("Un.Homme.Et.Une.Femme.1966.DVDRip.XviD.AR [PT ENG ESP]", ["english", "spanish", "portuguese"]),
    ("Geminis.2005.Argentina.ESP.ENG.PT.SUBS", ["english", "spanish", "portuguese"]),
    ("1917 2019 1080p Bluray x264-Sexmeup [Greek Subs] [Braveheart]", ["greek"]),
    ("The Lion King 1,2,3 Greek Language", ["greek"]),
    ("The Adams Family (1991) (Greek Subs integratet)", ["greek"]),
    ("6_Greek.srt", ["greek"]),
    ("The Insult (2017) [BluRay] [720p] Arabic", ["arabic"]),
    ("The.Mexican.2001 - Arabic Subs Hardcoded", ["arabic"]),
    ("Much Loved (2015) - DVDRip x265 HEVC - ARAB-ITA-FRE AUDIO (ENG S", ["english", "french", "italian", "arabic"]),
    ("42.2013.720p.BluRay.x264.HD4Ar Arab subtitle", ["arabic"]),
    ("Fauda.S01.HEBREW.1080p.NF.WEBRip.DD5.1.x264-TrollHD[rartv]", ["hebrew"]),
    ("madagascar 720p hebrew dubbed.mkv", ["hebrew"]),
    ("Into.the.Night.S01E04.Ayaz.1080p.NF.WEB-DL.DDP5.1.x264-NTG_track17_[heb].srt", ["hebrew"]),
    ("The.Protector.2018.S03.TURKISH.WEBRip.x264-ION10", ["turkish"]),
    ("Recep Ivedik 6 (2020) NETFLIX 720p WEBDL (Turkish) - ExtremlymTorrents", ["turkish"]),
    ("The Insider*1999*[DVD5][PAL][ENG, POL, sub. ROM, TUR]", ["english", "polish", "romanian", "turkish"]),
    ("Divorzio allitaliana [XviD - Ita Mp3 - Sub Eng Esp Tur]", ["english", "spanish", "italian", "turkish"]),
    ("2007 Saturno Contro [Saturn In Opposition] (ITA-FRA-TUR) [EngSub", ["english", "french", "italian", "turkish"]),
    ("Cowboy Bebop - 1080p BDrip Audio+sub MULTI (VF / VOSTFR)", ["multi audio", "french"]),
    ("Casablanca 1942 BDRip 1080p [multi language,multi subs].mkv", ["multi subs", "multi audio"]),
    ("Avengers.Endgame.2019.4K.UHD.ITUNES.DL.H265.Dolby.ATMOS.MSUBS-Deflate.Telly", ["multi subs"]),
    ("Dawn of the Planet of the Apes (2014) 720p BluRay x264 - MULTI S", ["multi subs"]),
    ("Pirates of the Caribbean On Stranger Tides (2011) DVD5 (Multi Su", ["multi subs"]),
    ("Jumanji The Next Level (2019) 720p HDCAM Ads Blurred x264 Dual A", ["multi audio"]),
    ("Men in Black International (2019) 720p Korsub HDRip x264 ESub [Dual Line Audio] [Hindi English]", ["dual audio", "english", "korean", "hindi"]),
    ("Fame (1980) [DVDRip][Dual][Ac3][Eng-Spa]", ["dual audio", "english", "spanish"]),
    ("O Rei do Show 2018 Dual Áudio 4K UtraHD By.Luan.Harper.", ["dual audio"]),
    ("Cowboy Bebop The Movie (2001) BD 1080p.x265.Tri-Audio.Ita.Eng.Jap [Rady]", ["multi audio", "english", "japanese", "italian"]),
    ("[IceBlue] Naruto (Season 01) - [Multi-Dub][Multi-Sub][HEVC 10Bits] 800p BD", ["multi subs", "multi audio"]),
    ("Blue Seed - 01 (BDRip 720x480p x265 HEVC FLAC, AC3x2 2.0x3)(Triple Audio)[sxales].mkv", ["multi audio"]),
    ("Ministri S01E02 SLOVAK 480p x264-mSD", ["slovakian"]),
    ("Subs/35_slo.srt", ["slovakian"]),
    ("Seinfeld.COMPLETE.SLOSUBS.DVDRip.XviD", ["slovakian"]),
    ("Subs/36_Slovenian.srt", ["slovakian"]),
    ("The House Bunny (2008) BDRemux 1080p MediaClub [RUS, UKR, ENG]", ["english", "russian", "ukrainian"]),
    ("L'immortel (2010) DVDRip AVC (Russian,Ukrainian)", ["russian", "ukrainian"]),
    ("Into.the.Night.S01E03.Mathieu.1080p.NF.WEB-DL.DDP5.1.x264-NTG_track33_[vie].srt", ["vietnamese"]),
    ("Subs/vie.srt", ["vietnamese"]),
    ("Subs/Vietnamese.vie.srt", ["vietnamese"]),
    ("Subs/Dear.S01E05.WEBRip.x265-ION265/25_may.srt", ["malay"]),
    ("Midnight.Diner.Tokyo.Stories.S02E10.WEBRip.x264-ION10/14_Indonesian.srt", ["indonesian"]),
    ("Inglês,Português,Italiano,Francês,Polonês,Russo,Norueguês,Dinamarquês,Alemão,Espanhol,Chinês,Japonês,Coreano,Persa,Hebraico,Sueco,Árabe,Holandês,Tâmil,Tailandês", ["english", "japanese", "korean", "chinese", "french", "spanish", "portuguese", "italian", "german", "russian", "tamil", "polish", "dutch", "danish", "swedish", "norwegian", "thai", "hebrew", "persian"]),
    ("russian,english,ukrainian", ["english", "russian", "ukrainian"]),
    ("Subs/Thai.srt", ["thai"]),
    ("Food Choices (2016) WEB.1080p.H264_tha.srt", ["thai"]),
    ("Ekk Deewana Tha (2012) DVDRip 720p x264 AAC TaRa.mkv", None),
    ("My Big Fat Greek Wedding (2002) 720p BrRip x264 - YIFY", None),
    ("Get Him to the Greek 2010 720p BluRay", None),
    ("[Hakata Ramen] Hoshiai No Sora (Stars Align) 01 [1080p][HEVC][x265][10bit][Dual-Subs] HR-DR", None),
    ("The English Patient (1996) 720p BrRip x264 - YIFY", None), # TODO: should have title "The English Patient"
    ("Do.Or.Die.1991.1080p.BluRay.x264-[YTS.LT].mp4", None),
    ("Castlevania 2017 1º temporada completa 1080p", None),
    ("City on a Hill - Temporada 1 [HDTV][Cap.110].avi", None),
    ("La inocencia [720p][wWw.EliteTorrent.NL].mkv", None),
    ("Reasonable Doubt - Temporada 1 [HDTV][Cap.101][www.AtomoHD.FI]", None),
    ("1883 - Temporada 1 [HDTV 720p][Cap.103][AC3 5.1][www.AtomoHD.fi]", None),
    ("Los Winchester - Temporada 1 [HDTV][Cap.103][www.atomoHD.tw]", None),
    ("El Inmortal- Temporada 1 [HDTV 720p][Cap.104][AC3 5.1][www.AtomoHD.ch]]", None),
    ("Black Friday (2021) [BluRay Rip][AC3 5.1][www.atomixHQ.TEL]", None),
    ("Deep Blue Sea 3 [HDR][wWw.EliteTorrent.SE]", None),
    ("The.Italian.Job.1969.1080p.BluRay.x265-RARBG.mp4", None),
    ("Chinese Zodiac (2012) 1080p BrRip x264 - YIFY", None),
    ("The German Doctor 2013 1080p WEBRip", None),
    ("Johnny English 2003 1080p BluRay", None),
    ("Polish Wedding (1998) 1080p (moviesbyrizzo upl).mp4", None),
    ("Russian.Doll.S02E02.2160p.NF.WEB-DL.DDP5.1.HDR.DV.HEVC-PEXA.mkv", None),
    ("The.Spanish.Prisoner.1997.1080p.BluRay.x265-RARBG", None),
    ("Japanese.Story.2003.1080p.WEBRip.x264-RARBG", None),
    ("[ Torrent9.cz ] The.InBetween.S01E10.FiNAL.HDTV.XviD-EXTREME.avi", None),
    ("Thai Massage (2022) 720p PDVDRip x264 AAC.mkv", None),
    ("Carson Daly 2017 09 13 Dan Harmon 720p HDTV x264-CROOKS", None),
    ("Dan Browns The Lost Symbol S01E03 1080p WEB H264-GLHF", None),
    ("Ben.Ara.2015.1080p.WEBRip.x265-RARBG.mp4", None),
    ("Ara.(A.Break).2008.DVDRip", None),
])
def test_languages_detection(parser, release_name, expected_languages):
    result = parser.parse(release_name)
    if expected_languages:
        assert "languages" in result, f"Languages code key missing in result for {release_name}"
        assert result["episodeCode"] == set(result["hdr"]) == set(expected_languages), f"Incorrect expected_languages detected for {release_name}"
    else:
        assert "languages" not in result, f"Incorrectly detected expected_languages code for {release_name}"
